#!/bin/bash

# # This program launches one run of iterated Race.
# # It should execute irace at some point like in:
# #
# # The simplest is to just invoke irace locally
BINDIR=$IRACE_HOME/bin
EXECDIR=runs
mkdir -p $EXECDIR
rm $EXECDIR/*
# shift 2
exec 2>&1
# exec 1> $EXECDIR/irace-$$.stdout 
$BINDIR/irace --exec-dir=$EXECDIR $* | tee $EXECDIR/irace.stdout
# #
# # All parameters are passed down to irace
# #
# # However, it could be much more complicated, see the examples in
# # examples/
